-- ============================================================
-- Modelo relacional: APEX Streaming
-- Plataforma de alquiler de películas
-- Compatible con Oracle Database 26ai
-- ============================================================

-- ============================================================
-- 1. Géneros
-- ============================================================
CREATE TABLE stream_generos (
    genero_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre          VARCHAR2(80 CHAR) NOT NULL,
    descripcion     VARCHAR2(500 CHAR),
    estado          VARCHAR2(15 CHAR) DEFAULT 'ACTIVO' NOT NULL,

    CONSTRAINT pk_stream_generos
        PRIMARY KEY (genero_id),

    CONSTRAINT uq_stream_generos_nombre
        UNIQUE (nombre),

    CONSTRAINT ck_stream_generos_estado
        CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

-- ============================================================
-- 2. Películas
-- ============================================================
CREATE TABLE stream_peliculas (
    pelicula_id             NUMBER GENERATED BY DEFAULT AS IDENTITY,
    titulo                  VARCHAR2(200 CHAR) NOT NULL,
    descripcion             CLOB,
    genero_id               NUMBER NOT NULL,
    anio                    NUMBER(4) NOT NULL,
    duracion_minutos        NUMBER(4) NOT NULL,
    clasificacion           VARCHAR2(10 CHAR) NOT NULL,
    pais_origen             VARCHAR2(100 CHAR) NOT NULL,
    fecha_estreno           DATE NOT NULL,
    idioma                  VARCHAR2(60 CHAR) NOT NULL,
    rating                  NUMBER(3,1),
    activo                  VARCHAR2(1 CHAR) DEFAULT 'S' NOT NULL,

    CONSTRAINT pk_stream_peliculas
        PRIMARY KEY (pelicula_id),

    CONSTRAINT fk_stream_peliculas_genero
        FOREIGN KEY (genero_id)
        REFERENCES stream_generos (genero_id),

    CONSTRAINT ck_stream_peliculas_anio
        CHECK (anio BETWEEN 1888 AND 2100),

    CONSTRAINT ck_stream_peliculas_duracion
        CHECK (duracion_minutos BETWEEN 1 AND 1440),

    CONSTRAINT ck_stream_peliculas_clasificacion
        CHECK (clasificacion IN ('G', 'PG', 'PG-13', 'R', 'NC-17', 'NR')), 

    CONSTRAINT ck_stream_peliculas_rating
        CHECK (rating BETWEEN 0 AND 10),

    CONSTRAINT ck_stream_peliculas_activo
        CHECK (activo IN ('S', 'N'))
);

-- Evita títulos duplicados con la misma fecha de estreno.
ALTER TABLE stream_peliculas
    ADD CONSTRAINT uq_stream_peliculas_titulo_fecha
    UNIQUE (titulo, fecha_estreno);

-- ============================================================
-- 3. Actores
-- ============================================================
CREATE TABLE stream_actores (
    actor_id                NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre                  VARCHAR2(100 CHAR) NOT NULL,
    apellido                VARCHAR2(100 CHAR) NOT NULL,
    fecha_nacimiento        DATE,
    nacionalidad            VARCHAR2(100 CHAR) NOT NULL,

    CONSTRAINT pk_stream_actores
        PRIMARY KEY (actor_id)
);

-- ============================================================
-- 4. Relación películas-actores
-- ============================================================
CREATE TABLE stream_pelicula_actor (
    pelicula_actor_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    pelicula_id             NUMBER NOT NULL,
    actor_id                NUMBER NOT NULL,
    personaje               VARCHAR2(150 CHAR),
    orden_credito           NUMBER(4),

    CONSTRAINT pk_stream_pelicula_actor
        PRIMARY KEY (pelicula_actor_id),

    CONSTRAINT fk_stream_pa_pelicula
        FOREIGN KEY (pelicula_id)
        REFERENCES stream_peliculas (pelicula_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_stream_pa_actor
        FOREIGN KEY (actor_id)
        REFERENCES stream_actores (actor_id)
        ON DELETE CASCADE,

    CONSTRAINT uq_stream_pa_pelicula_actor
        UNIQUE (pelicula_id, actor_id),

    CONSTRAINT ck_stream_pa_orden_credito
        CHECK (orden_credito IS NULL OR orden_credito >= 1)
);

-- ============================================================
-- 5. Clientes
-- ============================================================
CREATE TABLE stream_clientes (
    cliente_id              NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre                  VARCHAR2(100 CHAR) NOT NULL,
    apellido                VARCHAR2(100 CHAR) NOT NULL,
    email                   VARCHAR2(320 CHAR) NOT NULL,
    pais                    VARCHAR2(100 CHAR) NOT NULL,
    ciudad                  VARCHAR2(100 CHAR) NOT NULL,
    fecha_nacimiento        DATE NOT NULL,
    genero                  VARCHAR2(1 CHAR) NOT NULL,
    fecha_registro          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    activo                  VARCHAR2(1 CHAR) DEFAULT 'S' NOT NULL,

    CONSTRAINT pk_stream_clientes
        PRIMARY KEY (cliente_id),

    CONSTRAINT uq_stream_clientes_email
        UNIQUE (email),

    CONSTRAINT ck_stream_clientes_genero
        CHECK (genero IN ('F', 'M')),

    CONSTRAINT ck_stream_clientes_activo
        CHECK (activo IN ('S', 'N'))
);

-- ============================================================
-- 6. Alquileres
-- ============================================================
CREATE TABLE stream_alquileres (
    alquiler_id             NUMBER GENERATED BY DEFAULT AS IDENTITY,
    cliente_id              NUMBER NOT NULL,
    pelicula_id             NUMBER NOT NULL,
    fecha_alquiler           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    fecha_vencimiento        TIMESTAMP NOT NULL,
    fecha_devolucion         TIMESTAMP,
    precio                   NUMBER(10,2) DEFAULT 0 NOT NULL,
    estado                   VARCHAR2(15 CHAR) DEFAULT 'ACTIVO' NOT NULL,

    CONSTRAINT pk_stream_alquileres
        PRIMARY KEY (alquiler_id),

    CONSTRAINT fk_stream_alquileres_cliente
        FOREIGN KEY (cliente_id)
        REFERENCES stream_clientes (cliente_id),

    CONSTRAINT fk_stream_alquileres_pelicula
        FOREIGN KEY (pelicula_id)
        REFERENCES stream_peliculas (pelicula_id),

    CONSTRAINT ck_stream_alquileres_fechas
        CHECK (
            fecha_vencimiento >= fecha_alquiler
            AND (
                fecha_devolucion IS NULL
                OR fecha_devolucion >= fecha_alquiler
            )
        ),

    CONSTRAINT ck_stream_alquileres_precio
        CHECK (precio >= 0),

    CONSTRAINT ck_stream_alquileres_estado
        CHECK (estado IN ('ACTIVO', 'FINALIZADO','CANCELADO'))
);

-- ============================================================
-- Índices recomendados para claves foráneas y consultas APEX
-- ============================================================
CREATE INDEX ix_stream_peliculas_genero
    ON stream_peliculas (genero_id);

CREATE INDEX ix_stream_pa_actor
    ON stream_pelicula_actor (actor_id);

CREATE INDEX ix_stream_alquileres_cliente
    ON stream_alquileres (cliente_id);

CREATE INDEX ix_stream_alquileres_pelicula
    ON stream_alquileres (pelicula_id);

CREATE INDEX ix_stream_alquileres_estado
    ON stream_alquileres (estado);

CREATE INDEX ix_stream_alquileres_fecha
    ON stream_alquileres (fecha_alquiler);

-- ============================================================
-- Comentarios de documentación
-- ============================================================
COMMENT ON TABLE stream_generos IS
    'Catálogo de géneros cinematográficos.';

COMMENT ON TABLE stream_peliculas IS
    'Catálogo de películas disponibles en APEX Streaming.';

COMMENT ON TABLE stream_actores IS
    'Catálogo de actores.';

COMMENT ON TABLE stream_pelicula_actor IS
    'Relación muchos a muchos entre películas y actores.';

COMMENT ON TABLE stream_clientes IS
    'Clientes registrados en la plataforma.';

COMMENT ON TABLE stream_alquileres IS
    'Historial de alquileres de películas realizados por clientes.';

COMMENT ON COLUMN stream_peliculas.rating IS
    'Valoración de la película en una escala de 0 a 10.';

COMMENT ON COLUMN stream_peliculas.duracion_minutos IS
    'Duración de la película expresada en minutos.';

COMMENT ON COLUMN stream_alquileres.precio IS
    'Precio cobrado por el alquiler.';

-- ============================================================
-- Relaciones del modelo
-- ============================================================
-- STREAM_GENEROS 1 ---- N STREAM_PELICULAS
-- STREAM_PELICULAS N ---- N STREAM_ACTORES
--      mediante STREAM_PELICULA_ACTOR
-- STREAM_CLIENTES 1 ---- N STREAM_ALQUILERES
-- STREAM_PELICULAS 1 ---- N STREAM_ALQUILERES
-- ============================================================
